[book]
title = "pestパーサ入門"
description = "An introduction to the pest parser by implementing a Rust grammar subset"
author = ["Dragoș Tiselice", "高田 勝悟"]
language = "ja"

[output.html]
additional-js = ["highlight-pest.js"]
